In [1]:
import numpy as np


In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [10]:
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [11]:
y = np.array([[0],
              [1],
              [1],
              [0]])
y

array([[0],
       [1],
       [1],
       [0]])

In [6]:
np.random.seed(1)

In [7]:
weights_0 = 2 * np.random.random((3, 4)) - 1
weights_1 = 2 * np.random.random((4, 1)) - 1

In [8]:
num_iterations = 60000

In [9]:
learning_rate = 0.1

In [13]:
# Train the network
for i in range(num_iterations):
    
    # Forward propagation
    layer_0 = X
    layer_1 = sigmoid(np.dot(layer_0, weights_0))
    layer_2 = sigmoid(np.dot(layer_1, weights_1))
    
    # Backpropagation
    layer_2_error = y - layer_2
    layer_2_delta = layer_2_error * sigmoid_derivative(layer_2)
    layer_1_error = layer_2_delta.dot(weights_1.T)
    layer_1_delta = layer_1_error * sigmoid_derivative(layer_1)
    
    # Update the weights
    weights_1 += learning_rate * layer_1.T.dot(layer_2_delta)
    weights_0 += learning_rate * layer_0.T.dot(layer_1_delta)

In [14]:
print(layer_2)

[[0.00952977]
 [0.98778644]
 [0.98943064]
 [0.01421274]]
